# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f935eb3f-7bce-44d5-b48e-1f21b7021c9c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EAC8-67F6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data/hdd1" =
    { device = "/dev/mapper/hdd1";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."hdd1".device = "/dev/disk/by-uuid/49f2f43b-c616-4cef-b2fd-3363c8b46ad3";

  fileSystems."/var/lib/docker/overlay2/fc181f41972314551fc4019c57a959582b3e85c70a4211a2f4f75b5d6156a3ea/merged" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/data/hdd2" =
    { device = "/dev/disk/by-uuid/237083aa-7060-4071-9ef8-8cad75113497";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
