name = "htx"
author = "ahd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f52b83b175227ec5fb0f85a71e77bcfefc4c1d456ba935a4bad8c610a3bd6e5f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
