name = "htx"
author = "ahd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5654193bbce6082a8cc34924e7e63331a4b0a62d5039dfc4e54c373545a5060"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
