name = "htx"
author = "ahd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27aa960d072a62c207438c2c5a07d0684944e36b1cde29a0972b796333dbb7df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
