# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bc77ea84-e26a-4e9d-856d-4b9450bb22ed";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bc77ea84-e26a-4e9d-856d-4b9450bb22ed".device = "/dev/disk/by-uuid/bc77ea84-e26a-4e9d-856d-4b9450bb22ed";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/82E4-2306";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
